// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/private/auth/create': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/private/auth/create').default>>>>
    }
    '/api/private/auth/login': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/private/auth/login').default>>>>
    }
    '/api/private/auth/validate': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/private/auth/validate').default>>>>
    }
    '/api/private/model-data': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/api/private/model-data.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
  }
}
export {}