// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/28/2025, 7:51:43 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/kirillpanfile/Desktop/admin/nuxt-prisma-crm/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kirillpanfile/Desktop/admin/nuxt-prisma-crm/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kirillpanfile/Desktop/admin/nuxt-prisma-crm/src/plugins/**/*.{js,ts,mjs}","/Users/kirillpanfile/Desktop/admin/nuxt-prisma-crm/src/composables/**/*.{js,ts,mjs}","/Users/kirillpanfile/Desktop/admin/nuxt-prisma-crm/src/utils/**/*.{js,ts,mjs}","/Users/kirillpanfile/Desktop/admin/nuxt-prisma-crm/src/pages/admin.vue","/Users/kirillpanfile/Desktop/admin/nuxt-prisma-crm/src/pages/auth/login.vue","/Users/kirillpanfile/Desktop/admin/nuxt-prisma-crm/src/pages/admin-child.vue","/Users/kirillpanfile/Desktop/admin/nuxt-prisma-crm/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/kirillpanfile/Desktop/admin/nuxt-prisma-crm/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/kirillpanfile/Desktop/admin/nuxt-prisma-crm/src/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;